### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by CommanderRoot** [jb-lopez/php-extensions-windows#4]
PHP 8.3 was released on [23 Nov 2023](https://www.php.net/archive/2023.php#2023-11-23-2). It would be nice to have DLLs which are compatible with this new version

**Comment by jb-lopez** [comment]
The build has been updated and the 8.3 DLLs are available.

**Comment by CommanderRoot** [comment]
Thank you very much! Works like a charm
